In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors,metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
data=pd.read_csv('D:/EDA Datasets/car.data')

In [3]:
data.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [4]:
dict={'vhigh':'buying',
      'vhigh.1':'maintainence',
      '2':'doors',
      '2.1': 'Persons',
      'small':'luggage' ,
      'low':'safety',
      'unacc':'classification'}

In [5]:
data.rename(columns=dict,inplace=True)

In [6]:
data.head()

buying maintainence doors Persons luggage safety classification
0  vhigh        vhigh     2       2   small    med          unacc
1  vhigh        vhigh     2       2   small   high          unacc
2  vhigh        vhigh     2       2     med    low          unacc
3  vhigh        vhigh     2       2     med    med          unacc
4  vhigh        vhigh     2       2     med   high          unacc

In [7]:
#.values means X will take values of the 3 columns
X=data[[
       'buying',
       'maintainence',
       'safety'
]].values
y=data[['classification']]
print(X,y)

[['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ['vhigh' 'vhigh' 'low']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]      classification
0             unacc
1             unacc
2             unacc
3             unacc
4             unacc
...             ...
1722           good
1723          vgood
1724          unacc
1725           good
1726          vgood

[1727 rows x 1 columns]


In [8]:
#converting the data
#len(x[0]=3 columns i.e. buying maintainence safety)
#X[:,i]- It means all the rows of X and columns will be looped by i
Le=LabelEncoder()
for i in range(len(X[0])):
    X[:,i]=Le.fit_transform(X[:,i])

print(X)
#high values converted to3, low values to 1

[[3 3 2]
 [3 3 0]
 [3 3 1]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [9]:
#converting y
label_mapping={
    "unacc":0,
    "acc":1,
    "good":2,
    "vgood":3
}
y['classification']=y['classification'].map(label_mapping)
y=np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-9-f86e257c9f02>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['classification']=y['classification'].map(label_mapping)


In [10]:
#creating the model
knn=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

In [11]:
#Train the model
#knn.fit(). this trains the model.To determine the accuracy we need to separate data into 2 categories trining and test data.
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)
knn.fit(X_train,y_train)
#Making predictions after training
prediction=knn.predict(X_test)
#calculating the accuracy
accuracy=metrics.accuracy_score(y_test, prediction)
print(prediction)
print(accuracy)


[1 0 0 2 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 2 2 0 0 0 2 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 2 0 0 0 0 0 0 0 2 0
 0 0 0 1 0 0 1 1 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 1
 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 2 0 1 0 2 0 0 1 0 0 1 0 0
 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 1 1 2
 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 0 0 0 0 0
 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 2 0 0 0 2 0 2 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 2 0 1 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0
 0 0 1 0 0 1 0 0 0 1 0 1 0]
0.7456647398843931


C:\Users\Dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [13]:
print('actual value:',y[20])
print('prediction:',knn.predict(X)[20])

actual value: [0]
prediction: 0


In [15]:
a=550
print('actual value:',y[a])
print('prediction:',knn.predict(X)[a])

actual value: [1]
prediction: 1
